version: '3.8'

services:
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8080"
    restart: unless-stopped