server:
  port: 8080
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/inquiry-service-cert.p12
#    key-store-password: ${SSL_KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: inquiry-service-cert

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: inquiry

  liquibase:
    enabled: true
    change-log: db/changelog-cumulative.yaml
    default-schema: inquiry
    contexts: development
