app:
  outbox:
    batch-size: 50
    poll-interval-ms: 20_000
  keycloak:
    url: http://localhost:8082

server:
  port: 8082
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore/inquiry-service-cert.p12
#    key-store-password: ${SSL_KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: inquiry-service-cert

spring:
  application:
    name: inquiry-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: inquiry

  liquibase:
    enabled: true
    change-log: db/changelog-cumulative.yaml
    default-schema: inquiry
    contexts: development

  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      properties:
        spring.json.trusted.packages: "*"
        request.timeout.ms: 60_000
        session.timeout.ms: 45_000
        heartbeat.interval.ms: 3_000
        max.poll.interval.ms: 300_000
        fetch.max.wait.ms: 500
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db,kafka,keycloak"
