app:
  keycloak:
    url: http://keycloak:8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.url}/realms/iprody
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://customer-postgres:5432/customer
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: INFO