server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: payment

  liquibase:
    enabled: true
    change-log: db/changelog-cumulative.yaml
    default-schema: payment
    contexts: development