app:
  outbox:
    batch-size: 50
    poll-interval-ms: 60_000
  payment-provider:
    url: "http://localhost:9999/charges"
    credentials:
      user: "paymentAgentIprody"
      pwd: "iprodyTestPassword0123"

server:
  port: 8081

spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: payment

  config:
    import: "application-logging.yml"

  liquibase:
    enabled: true
    change-log: db/changelog-cumulative.yaml
    default-schema: payment
    contexts: development
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      properties:
        spring.json.trusted.packages: "*"
        request.timeout.ms: 60_000
        session.timeout.ms: 45_000
        heartbeat.interval.ms: 3_000
        max.poll.interval.ms: 300_000
        fetch.max.wait.ms: 500
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db,kafka"
        external:
          include: "payment-provider"
