### getById
GET http://localhost:8080/api/v1/inquires/98908056-69fd-4733-8824-b91e39c37d19

### save
POST http://localhost:8080/api/v1/inquires
Content-Type: application/json

{
  "customerRefId": "aeb380eb-0f6c-4ed9-9ff4-94a7e611e2c1",
  "managerRefId": "ea70139f-46e1-4f86-b96f-fdc47a22c943",
  "productRefId": "26deb803-f4e5-460a-a1a5-88f82140c796",
  "source": "web"
}

### update
PUT http://localhost:8080/api/v1/inquires/98908056-69fd-4733-8824-b91e39c37d19
Content-Type: application/json

{
  "pagination": {
    "offset": 9007199254740991,
    "limit": 1073741824
  },
  "sorting": "FULL_NAME",
  "filter": {
    "fullName": "string"
  }
}

### search
GET http://localhost:8080/api/v1/inquires/search
    ?pagination.offset=0
    &pagination.limit=10
    &filter.fullName=DenisM
    &sorting.sortField=FULL_NAME
    &sorting.sortDirection=ASC

### canceled
POST http://localhost:8080/api/v1/inquires/cancel
Content-Type: application/json

{
  "id": "f55e59ca-1d66-4259-b082-c4784f160b9f",
  "status":"SUCCESS",
  "reason":"Test cancellation222"
}