app:
  outbox:
    batch-size: 50
    poll-interval-ms: 60_000

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: inventory

  liquibase:
    enabled: true
    change-log: db/changelog-cumulative.yaml
    default-schema: inventory
    contexts: development
