
### get token for user
POST http://localhost:8084/realms/iprody/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username = admin &
password = password123 &
grant_type = password &
client_id = iprody-public-client

> {%
    client.global.set("auth_access_token", response.body.access_token);
    console.log(response.body.access_token)
%}

### getById
GET http://localhost:8080/api/v1/customers/98908056-69fd-4733-8824-b91e39c37d19
Authorization: Bearer {{auth_access_token}}

### save
POST http://localhost:8080/api/v1/customers
Authorization: Bearer {{auth_access_token}}
Content-Type: application/json

{
  "fullName": "DenisM",
  "contract": {
    "email": "124@mail.ru3",
    "phoneNumber": "+71234567893"
  }
}

### update
PUT http://localhost:8080/api/v1/customers/98908056-69fd-4733-8824-b91e39c37d19
Authorization: Bearer {{auth_access_token}}
Content-Type: application/json

{
  "pagination": {
    "offset": 9007199254740991,
    "limit": 1073741824
  },
  "sorting": "FULL_NAME",
  "filter": {
    "fullName": "string"
  }
}

### search
GET http://localhost:8080/api/v1/customers/search
    ?pagination.offset=0
    &pagination.limit=10
    &filter.fullName=DenisM
    &sorting.sortField=FULL_NAME
    &sorting.sortDirection=ASC
Authorization: Bearer {{auth_access_token}}